#!/usr/bin/env python3
"""Normalize Chinese Markdown table captions for publication.

Rules:
- A table caption should appear before the Markdown table.
- If the same table has a generic caption before it and a more specific caption
  after it, keep the latter and move it before the table.
- Do not invent captions in this script.
"""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ZH = ROOT / "docs" / "zh"

CAPTION_RE = re.compile(r"^\*表\s*((?:P\d{1,2}|\d+|[A-Z])\s*[-—]\s*\d+)\s*[:：].*\*\s*$")
TABLE_SEP_RE = re.compile(r"^\s*\|?\s*:?-{3,}:?\s*(\|\s*:?-{3,}:?\s*)+\|?\s*$")
GENERIC_TITLES = (
    "项目验收与复核口径",
    "关键要点与工程复核口径",
    "字段说明与复核口径",
    "阶段、产物与复核字段",
    "风险、控制措施与复核口径",
)


def is_caption(line: str) -> bool:
    return CAPTION_RE.match(line.strip()) is not None


def label_of(line: str) -> str | None:
    m = CAPTION_RE.match(line.strip())
    if not m:
        return None
    return re.sub(r"\s+", "", m.group(1).replace("—", "-")).upper()


def is_generic_caption(line: str) -> bool:
    return any(title in line for title in GENERIC_TITLES)


def previous_nonblank(lines: list[str], idx: int) -> int | None:
    j = idx - 1
    while j >= 0 and not lines[j].strip():
        j -= 1
    return j if j >= 0 else None


def next_nonblank(lines: list[str], idx: int) -> int | None:
    j = idx
    while j < len(lines) and not lines[j].strip():
        j += 1
    return j if j < len(lines) else None


def table_blocks(lines: list[str]) -> list[tuple[int, int]]:
    blocks: list[tuple[int, int]] = []
    i = 0
    while i < len(lines) - 1:
        if "|" in lines[i] and TABLE_SEP_RE.match(lines[i + 1]):
            start = i
            end = i + 2
            while end < len(lines) and "|" in lines[end]:
                end += 1
            blocks.append((start, end))
            i = end
        else:
            i += 1
    return blocks


def normalize_file(path: Path) -> int:
    lines = path.read_text(encoding="utf-8").splitlines(True)
    changed = 0

    while True:
        moved = False
        for start, end in table_blocks(lines):
            prev = previous_nonblank(lines, start)
            nxt = next_nonblank(lines, end)
            prev_caption = prev is not None and is_caption(lines[prev])
            next_caption = nxt is not None and is_caption(lines[nxt])

            if not next_caption:
                continue

            next_line = lines[nxt]
            next_label = label_of(next_line)

            if prev_caption and label_of(lines[prev]) == next_label:
                # Prefer the more specific caption. In project chapters, the
                # autogenerated generic caption often sits before the table.
                if is_generic_caption(lines[prev]) or len(lines[prev]) <= len(next_line):
                    del lines[nxt]
                    if nxt < len(lines) and not lines[nxt].strip():
                        del lines[nxt]
                    lines[prev] = next_line if next_line.endswith("\n") else next_line + "\n"
                    changed += 1
                    moved = True
                    break
                else:
                    del lines[nxt]
                    changed += 1
                    moved = True
                    break

            if not prev_caption:
                del lines[nxt]
                if nxt < len(lines) and not lines[nxt].strip():
                    del lines[nxt]
                insert_at = start
                lines.insert(insert_at, next_line if next_line.endswith("\n") else next_line + "\n")
                lines.insert(insert_at + 1, "\n")
                changed += 1
                moved = True
                break

        if not moved:
            break

    if changed:
        path.write_text("".join(lines), encoding="utf-8")
    return changed


def main() -> None:
    total = 0
    changed_files = 0
    for path in sorted(ZH.rglob("*.md")):
        n = normalize_file(path)
        if n:
            changed_files += 1
            total += n
            print(f"{path.relative_to(ROOT)} {n}")
    print(f"changed_files={changed_files} moves={total}")


if __name__ == "__main__":
    main()
